name: Chengang Sun
author: Chengang Sun
baseurl: ''
description: technical blog
github: http://www.github.com/ChengangSun
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: www.linkedin.com/in/chengang-sun
email: ChengangSun@gmail.com/c59sun@edu.uwaterloo.ca
location: Waterloo, ON, Canada
disqus: diqus-scg

##Make sure to edit the above fields, especially for disqus.


highlighter: rogue

kramdown:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
